
# Generated by Qodo Gen

# Dependencies:
# pip install pytest-mock
import pytest

class TestLancedbBrowser:

    # Initializes session state variables when not present
    def test_initializes_session_state_variables(self, mocker):
        # Setup
        mocker.patch('streamlit.session_state', {})
        mocker.patch('components.lancedb_browser.is_running_in_docker', return_value=False)
    
        # Execute
        from components.lancedb_browser import lancedb_browser
        lancedb_browser()
    
        # Assert
        import streamlit as st
        assert 'lancedb_connected' in st.session_state
        assert st.session_state.lancedb_connected is False
        assert 'lancedb_connection' in st.session_state
        assert st.session_state.lancedb_connection is None
        assert 'lancedb_tables' in st.session_state
        assert st.session_state.lancedb_tables == []
        assert 'current_table' in st.session_state
        assert st.session_state.current_table is None

    # Handles case when running in Docker but HOST_DB_PATH is not set
    def test_docker_without_host_db_path(self, mocker):
        # Setup
        mocker.patch('streamlit.session_state', {
            'lancedb_connected': False,
            'lancedb_connection': None,
            'lancedb_tables': [],
            'current_table': None
        })
        mocker.patch('components.lancedb_browser.is_running_in_docker', return_value=True)
        mocker.patch.dict('os.environ', {}, clear=True)  # Empty environment variables
        mock_connect = mocker.patch('components.lancedb_browser.connect')
        mock_list_tables = mocker.patch('components.lancedb_browser.list_lancedb_tables')
        mock_expander = mocker.patch('streamlit.expander')
        mock_connect_to_lancedb = mocker.patch('components.lancedb_browser.connect_to_lancedb')
    
        # Execute
        from components.lancedb_browser import lancedb_browser
        lancedb_browser()
    
        # Assert
        mock_connect.assert_not_called()
        mock_list_tables.assert_not_called()
        mock_expander.assert_called_once()
        mock_connect_to_lancedb.assert_called_once()